name: Build and Test

on: 
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      - uses: RafikFarhad/clang-format-github-action@v7

      - name: Install libcurl development headers
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Build main
        run: |
          make

      - name: Run Tests
        run: | 
          make test